; PlatformIO Configuration
; M5Stack Core2 - SCD41 CO2 Sensor Logger
;
; June 2026 - Tetsu Nishimura

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200

lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    sensirion/Sensirion I2C SCD4x
    lvgl/lvgl@^8.3.11

build_flags =
    -I include
    -DCORE_DEBUG_LEVEL=0
    -D LV_CONF_INCLUDE_SIMPLE

; パーティションスキームの設定 (Minimal SPIFFS: 1.9MB APP / 190KB SPIFFS)
board_build.partitions = min_spiffs.csv
